let raidPokemon5 = {
  pokemon: [
    {
      name: "Raichu",
      type: ["electric", "steel"],
      meta: [""],
    },
    {
      name: "Arcanine",
      type: ["fire", "dark", "normal"],
      meta: [""],
    },
    {
      name: "Slowbro",
      type: ["water", "ghost", "psychic"],
      meta: [""],
    },
    {
      name: "Cloyster",
      type: ["water", "ice", "normal"],
      meta: [""],
    },
    {
      name: "Gengar",
      type: ["ghost", "poison"],
      meta: [""],
    },
    {
      name: "Scyther",
      type: ["flying", "bug", "normal"],
      meta: [""],
    },
    {
      name: "Tauros(Fire)",
      type: ["fire", "normal", "fighting"],
      meta: [""],
    },
    {
      name: "Tauros(Water)",
      type: ["water", "normal", "fighting"],
      meta: [""],
    },
    {
      name: "Gyarados",
      type: ["water", "dragon", "dark", "flying"],
      meta: [""],
    },
    // {
    //   name: "Ditto",
    //   type: ["ditto"],
    //   meta: [""],
    // },
    {
      name: "Eevee",
      type: ["normal", "ghost", "fighting"],
      meta: [""],
    },
    {
      name: "Dragonite",
      type: ["dragon", "flying", "normal"],
      meta: [""],
    },
    {
      name: "Slowking",
      type: ["psychic", "water"],
      meta: [""],
    },
    {
      name: "Scizor",
      type: ["bug", "steel", "grass", "normal"],
      meta: [""],
    },
    {
      name: "Delibird",
      type: ["ice", "normal", "flying"],
      meta: [""],
    },
    {
      name: "Houndoom",
      type: ["dark", "fire"],
      meta: [""],
    },
    {
      name: "Blissey",
      type: ["normal", "fairy", "fighting"],
      meta: [""],
    },
    {
      name: "Tyranitar",
      type: ["rock", "dark"],
      meta: [""],
    },
    {
      name: "Gardevoir",
      type: ["psychic", "fairy"],
      meta: [""],
    },
    {
      name: "Breloom",
      type: ["grass", "fighting", "normal"],
      meta: [""],
    },
    {
      name: "Slaking",
      type: ["ghost", "fairy", "normal"],
      meta: [""],
    },
    {
      name: "Hariyama",
      type: ["fighting", "water", "steel"],
      meta: [""],
    },
    {
      name: "Sableye",
      type: ["dark", "ghost"],
      meta: [""],
    },
    {
      name: "Camerupt",
      type: ["ground", "fire"],
      meta: [""],
    },
    {
      name: "Altaria",
      type: ["flying", "dragon"],
      meta: [""],
    },
    {
      name: "Glalie",
      type: ["ice", "dark", "normal"],
      meta: [""],
    },
    {
      name: "Salamence",
      type: ["dragon", "flying", "normal"],
      meta: [""],
    },
    {
      name: "Staraptor",
      type: ["flying", "normal", "fighting"],
      meta: [""],
    },
    {
      name: "Luxray",
      type: ["dark", "electric", "fighting"],
      meta: [""],
    },
    {
      name: "Drifblim",
      type: ["flying", "ghost"],
      meta: [""],
    },
    {
      name: "Mismagius",
      type: ["fire", "ghost"],
      meta: [""],
    },
    {
      name: "Honchkrow",
      type: ["dark", "flying"],
      meta: [""],
    },
    {
      name: "Bronzong",
      type: ["steel", "psychic", "dark"],
      meta: [""],
    },
    {
      name: "Garchomp",
      type: ["dragon", "ground", "steel", "normal"],
      meta: [""],
    },
    {
      name: "Hippowdon",
      type: ["rock", "ground", "normal"],
      meta: [""],
    },
    {
      name: "Abomasnow",
      type: ["ice", "grass"],
      meta: [""],
    },
    {
      name: "Weavile",
      type: ["dark", "ice"],
      meta: [""],
    },
    {
      name: "Magnezone",
      type: ["steel", "electric"],
      meta: [""],
    },
    {
      name: "Gallade",
      type: ["psychic", "fighting", "bug", "ghost"],
      meta: [""],
    },
    {
      name: "Froslass",
      type: ["ice", "ghost", "fairy"],
      meta: [""],
    },
    {
      name: "Rotom",
      type: ["electric", "ghost", "normal"],
      meta: [""],
    },
    {
      name: "Krookodile",
      type: ["ground", "dark", "normal"],
      meta: [""],
    },
    {
      name: "Zoroark",
      type: ["dark", "normal"],
      meta: [""],
    },
    {
      name: "Gothitelle",
      type: ["psychic", "electric"],
      meta: [""],
    },
    {
      name: "Amoonguss",
      type: ["grass", "poison"],
      meta: [""],
    },
    {
      name: "Eelektross",
      type: ["fire", "electric", "normal"],
      meta: [""],
    },
    {
      name: "Haxorus",
      type: ["dragon", "dark", "normal", "bug"],
      meta: [""],
    },
    {
      name: "Braviary",
      type: ["flying", "normal", "fighting", "dark"],
      meta: [""],
    },
    {
      name: "Hydreigon",
      type: ["dark", "dragon"],
      meta: [""],
    },
    {
      name: "Volcarona",
      type: ["fire", "bug", "flying"],
      meta: [""],
    },
    {
      name: "Talonflame",
      type: ["fire", "steel", "flying"],
      meta: [""],
    },
    {
      name: "Florger",
      type: ["grass", "fairy", "psychic"],
      meta: [""],
    },
    {
      name: "Dragalge",
      type: ["dragon", "water", "poison"],
      meta: [""],
    },
    {
      name: "Clawitzer",
      type: ["water", "fighting", "dragon"],
      meta: [""],
    },
    {
      name: "Goodra",
      type: ["water", "poison", "dragon", "grass"],
      meta: [""],
    },
    {
      name: "Avalugg",
      type: ["dark", "ice", "normal"],
      meta: [""],
    },
    {
      name: "Noivern",
      type: ["flying", "dragon", "normal"],
      meta: [""],
    },
    {
      name: "Mudsdale",
      type: ["fighting", "steel", "ground", "fighting"],
      meta: [""],
    },
    {
      name: "Tsareena",
      type: ["grass", "normal", "fighting"],
      meta: [""],
    },
    {
      name: "Oranguru",
      type: ["psychic", "normal"],
      meta: [""],
    },
    {
      name: "Passimian",
      type: ["fighting", "poison", "normal", "grass"],
      meta: [""],
    },
    {
      name: "Mimikyu",
      type: ["fairy", "ghost"],
      meta: [""],
    },
    {
      name: "Greedent",
      type: ["normal", "grass", "fighting"],
      meta: [""],
    },
    {
      name: "Corviknight",
      type: ["flying", "steel", "fighting", "dark"],
      meta: [""],
    },
    {
      name: "Coalossal",
      type: ["rock", "fire"],
      meta: [""],
    },
    {
      name: "Flapple",
      type: ["dragon", "grass"],
      meta: [""],
    },
    {
      name: "Appletun",
      type: ["dragon", "grass", "fighting"],
      meta: [""],
    },
    {
      name: "Toxtricity",
      type: ["poison", "electric", "normal"],
      meta: [""],
    },
    {
      name: "Polteageist",
      type: ["ghost", "grass", "normal"],
      meta: [""],
    },
    {
      name: "Hatterena",
      type: ["psychic", "dark", "fairy"],
      meta: [""],
    },
    {
      name: "Grimmsnarl",
      type: ["dark", "fairy"],
      meta: [""],
    },
    {
      name: "Falinks",
      type: ["normal", "fighting", "bug"],
      meta: [""],
    },
    {
      name: "Pincurchin",
      type: ["electric", "poison", "water"],
      meta: [""],
    },
    {
      name: "indeedee",
      type: ["psychic", "normal", "ghost"],
      meta: [""],
    },
    {
      name: "Copperajah",
      type: ["normal", "ghost", "ground"],
      meta: [""],
    },
    {
      name: "Dragapult",
      type: ["ghost", "dragon", "electric"],
      meta: [""],
    },
    {
      name: "Pawmot",
      type: ["electric", "fighting"],
      meta: [""],
    },
    {
      name: "Arboliva",
      type: ["grass", "normal", "ground"],
      meta: [""],
    },
    {
      name: "Garganacl",
      type: ["rock", "fighting"],
      meta: [""],
    },
    {
      name: "Armarouge",
      type: ["ghost", "fire", "psychic"],
      meta: [""],
    },
    {
      name: "Ceruledge",
      type: ["ghost", "fire", "psychic"],
      meta: [""],
    },
    {
      name: "Mabosstiff",
      type: ["dark", "fairy", "normal"],
      meta: [""],
    },
    {
      name: "Brambleghast",
      type: ["grass", "ghost", "bug"],
      meta: [""],
    },
    {
      name: "Tinkaton",
      type: ["fairy", "steel", "dark", "fighting"],
      meta: [""],
    },
    {
      name: "Bombirdier",
      type: ["rock", "dark", "flying", "fighting"],
      meta: [""],
    },
    {
      name: "Palafin",
      type: ["water", "flying", "normal"],
      meta: [""],
    },
    {
      name: "Revavroom",
      type: ["poison", "fire", "steel"],
      meta: [""],
    },
    {
      name: "Orthworm",
      type: ["ground", "steel", "normal"],
      meta: [""],
    },
    {
      name: "Glimmora",
      type: ["poison", "rock", "normal"],
      meta: [""],
    },
    {
      name: "Glimmora (Tera Blast Fire)",
      type: ["poison", "rock", "normal", "fire"],
      meta: [""],
    },
    {
      name: "Glimmora (Tera Blast Water)",
      type: ["poison", "rock", "normal", "water"],
      meta: [""],
    },
    {
      name: "Glimmora (Tera Blast Grass)",
      type: ["poison", "rock", "normal", "grass"],
      meta: [""],
    },
    {
      name: "Glimmora (Tera Blast Electric)",
      type: ["poison", "rock", "normal", "electric"],
      meta: [""],
    },
    {
      name: "Glimmora (Tera Blast Ice)",
      type: ["poison", "rock", "normal", "ice"],
      meta: [""],
    },
    {
      name: "Glimmora (Tera Blast Fighting)",
      type: ["poison", "rock", "normal", "fighting"],
      meta: [""],
    },
    {
      name: "Glimmora (Tera Blast Ground)",
      type: ["poison", "rock", "normal", "ground"],
      meta: [""],
    },
    {
      name: "Glimmora (Tera Blast Flying)",
      type: ["poison", "rock", "normal", "flying"],
      meta: [""],
    },
    {
      name: "Glimmora (Tera Blast Psychic)",
      type: ["poison", "rock", "normal", "psychic"],
      meta: [""],
    },
    {
      name: "Glimmora (Tera Blast Bug)",
      type: ["poison", "rock", "normal", "bug"],
      meta: [""],
    },
    {
      name: "Glimmora (Tera Blast Ghost)",
      type: ["poison", "rock", "normal", "ghost"],
      meta: [""],
    },
    {
      name: "Glimmora (Tera Blast Dark)",
      type: ["poison", "rock", "normal", "dark"],
      meta: [""],
    },
    {
      name: "Glimmora (Tera Blast Dragon)",
      type: ["poison", "rock", "normal", "dragon"],
      meta: [""],
    },
    {
      name: "Glimmora (Tera Blast Steel)",
      type: ["poison", "rock", "normal", "steel"],
      meta: [""],
    },
    {
      name: "Glimmora (Tera Blast Fairy)",
      type: ["poison", "rock", "normal", "fairy"],
      meta: [""],
    },
    {
      name: "Cetitan",
      type: ["ice", "water"],
      meta: [""],
    },
    {
      name: "Tatsugiri",
      type: ["water", "dragon", "normal"],
      meta: [""],
    },
    {
      name: "Annihilape",
      type: ["ghost", "fighting", "dragon"],
      meta: [""],
    },
    {
      name: "Kingambit",
      type: ["dark", "steel"],
      meta: [""],
    },
    {
      name: "Baxcalibur",
      type: ["ice", "dragon", "fighting"],
      meta: [""],
    },
  ],
};

let raidPokemon6 = {
  //some pokemon in 6 star raid have Tera Blast, this type is notated as 'tera"
  pokemon: [
    {
      name: "Gengar",
      type: ["ghost", "poison", "fairy"],
      meta: [""],
    },
    {
      name: "Tauros(Fighting)",
      type: ["fire", "normal", "fighting"],
      meta: [""],
    },
    {
      name: "Tauros(Fire)",
      type: ["fire", "normal", "fighting"],
      meta: [""],
    },
    {
      name: "Tauros(Water)",
      type: ["water", "normal", "fighting"],
      meta: [""],
    },
    {
      name: "Gyarados",
      type: ["water", "ice", "dark", "flying"],
      meta: [""],
    },
    // {
    //   name: "Ditto",
    //   type: ["ditto"],
    //   meta: [""],
    // },
    {
      name: "Vaporeon",
      type: ["water", "normal"],
      meta: [""],
    },
    {
      name: "Vaporeon (Tera Blast Fire)",
      type: ["water", "normal", "fire"],
      meta: [""],
    },
    {
      name: "Vaporeon (Tera Blast Grass)",
      type: ["water", "normal", "grass"],
      meta: [""],
    },
    {
      name: "Vaporeon (Tera Blast Electric)",
      type: ["water", "normal", "electric"],
      meta: [""],
    },
    {
      name: "Vaporeon (Tera Blast Ice)",
      type: ["water", "normal", "ice"],
      meta: [""],
    },
    {
      name: "Vaporeon (Tera Blast Fighting)",
      type: ["water", "normal", "fighting"],
      meta: [""],
    },
    {
      name: "Vaporeon (Tera Blast Poison)",
      type: ["water", "normal", "poison"],
      meta: [""],
    },
    {
      name: "Vaporeon (Tera Blast Ground)",
      type: ["water", "normal", "ground"],
      meta: [""],
    },
    {
      name: "Vaporeon (Tera Blast Flying)",
      type: ["water", "normal", "flying"],
      meta: [""],
    },
    {
      name: "Vaporeon (Tera Blast Psychic)",
      type: ["water", "normal", "psychic"],
      meta: [""],
    },
    {
      name: "Vaporeon (Tera Blast Bug)",
      type: ["water", "normal", "bug"],
      meta: [""],
    },
    {
      name: "Vaporeon (Tera Blast Rock)",
      type: ["water", "normal", "rock"],
      meta: [""],
    },
    {
      name: "Vaporeon (Tera Blast Ghost)",
      type: ["water", "normal", "ghost"],
      meta: [""],
    },
    {
      name: "Vaporeon (Tera Blast Dark)",
      type: ["water", "normal", "dark"],
      meta: [""],
    },
    {
      name: "Vaporeon (Tera Blast Dragon)",
      type: ["water", "normal", "dragon"],
      meta: [""],
    },
    {
      name: "Vaporeon (Tera Blast Steel)",
      type: ["water", "normal", "steel"],
      meta: [""],
    },
    {
      name: "Vaporeon (Tera Blast Fairy)",
      type: ["water", "normal", "fairy"],
      meta: [""],
    },
    {
      name: "Jolteon",
      type: ["electric", "ghost"],
      meta: [""],
    },
    {
      name: "Jolteon(Tera Blast Normal)",
      type: ["electric", "ghost", "normal"],
      meta: [""],
    },
    {
      name: "Jolteon(Tera Blast Fire)",
      type: ["electric", "ghost", "fire"],
      meta: [""],
    },
    {
      name: "Jolteon(Tera Blast Water)",
      type: ["electric", "ghost", "water"],
      meta: [""],
    },
    {
      name: "Jolteon(Tera Blast Grass)",
      type: ["electric", "ghost", "grass"],
      meta: [""],
    },
    {
      name: "Jolteon(Tera Blast Ice)",
      type: ["electric", "ghost", "ice"],
      meta: [""],
    },
    {
      name: "Jolteon(Tera Blast Fighting)",
      type: ["electric", "ghost", "fighting"],
      meta: [""],
    },
    {
      name: "Jolteon(Tera Blast Poison)",
      type: ["electric", "ghost", "poison"],
      meta: [""],
    },
    {
      name: "Jolteon(Tera Blast Ground)",
      type: ["electric", "ghost", "ground"],
      meta: [""],
    },
    {
      name: "Jolteon(Tera Blast Flying)",
      type: ["electric", "ghost", "flying"],
      meta: [""],
    },
    {
      name: "Jolteon(Tera Blast Psychic)",
      type: ["electric", "ghost", "psychic"],
      meta: [""],
    },
    {
      name: "Jolteon(Tera Blast Bug)",
      type: ["electric", "ghost", "bug"],
      meta: [""],
    },
    {
      name: "Jolteon(Tera Blast Rock)",
      type: ["electric", "ghost", "rock"],
      meta: [""],
    },
    {
      name: "Jolteon(Tera Blast Dark)",
      type: ["electric", "ghost", "dark"],
      meta: [""],
    },
    {
      name: "Jolteon(Tera Blast Dragon)",
      type: ["electric", "ghost", "dragon"],
      meta: [""],
    },
    {
      name: "Jolteon(Tera Blast Steel)",
      type: ["electric", "ghost", "steel"],
      meta: [""],
    },
    {
      name: "Jolteon(Tera Blast Fairy)",
      type: ["electric", "ghost", "fairy"],
      meta: [""],
    },
    {
      name: "Flareon",
      type: ["fire", "ghost"],
      meta: [""],
    },
    {
      name: "Flareon (Tera Blast Normal)",
      type: ["fire", "ghost", "normal"],
      meta: [""],
    },
    {
      name: "Flareon (Tera Blast Water)",
      type: ["fire", "ghost", "water"],
      meta: [""],
    },
    {
      name: "Flareon (Tera Blast Grass)",
      type: ["fire", "ghost", "grass"],
      meta: [""],
    },
    {
      name: "Flareon (Tera Blast Electric)",
      type: ["fire", "ghost", "electric"],
      meta: [""],
    },
    {
      name: "Flareon (Tera Blast Ice)",
      type: ["fire", "ghost", "ice"],
      meta: [""],
    },
    {
      name: "Flareon (Tera Blast Fighting)",
      type: ["fire", "ghost", "fighting"],
      meta: [""],
    },
    {
      name: "Flareon (Tera Blast Poison)",
      type: ["fire", "ghost", "poison"],
      meta: [""],
    },
    {
      name: "Flareon (Tera Blast Ground)",
      type: ["fire", "ghost", "ground"],
      meta: [""],
    },
    {
      name: "Flareon (Tera Blast Flying)",
      type: ["fire", "ghost", "flying"],
      meta: [""],
    },
    {
      name: "Flareon (Tera Blast Psychic)",
      type: ["fire", "ghost", "psychic"],
      meta: [""],
    },
    {
      name: "Flareon (Tera Blast Bug)",
      type: ["fire", "ghost", "bug"],
      meta: [""],
    },
    {
      name: "Flareon (Tera Blast Rock)",
      type: ["fire", "ghost", "rock"],
      meta: [""],
    },
    {
      name: "Flareon (Tera Blast Dark)",
      type: ["fire", "ghost", "dark"],
      meta: [""],
    },
    {
      name: "Flareon (Tera Blast Dragon)",
      type: ["fire", "ghost", "dragon"],
      meta: [""],
    },
    {
      name: "Flareon (Tera Blast Steel)",
      type: ["fire", "ghost", "steel"],
      meta: [""],
    },
    {
      name: "Flareon (Tera Blast Fairy)",
      type: ["fire", "ghost", "fairy"],
      meta: [""],
    },
    {
      name: "Espeon",
      type: ["psychic"],
      meta: [""],
    },
    {
      name: "Espeon (Tera Blast Normal)",
      type: ["psychic", "normal"],
      meta: [""],
    },
    {
      name: "Espeon (Tera Blast Fire)",
      type: ["psychic", "fire"],
      meta: [""],
    },
    {
      name: "Espeon (Tera Blast Water)",
      type: ["psychic", "water"],
      meta: [""],
    },
    {
      name: "Espeon (Tera Blast Grass)",
      type: ["psychic", "grass"],
      meta: [""],
    },
    {
      name: "Espeon (Tera Blast Electric)",
      type: ["psychic", "electric"],
      meta: [""],
    },
    {
      name: "Espeon (Tera Blast Ice)",
      type: ["psychic", "ice"],
      meta: [""],
    },
    {
      name: "Espeon (Tera Blast Fighting)",
      type: ["psychic", "fighting"],
      meta: [""],
    },
    {
      name: "Espeon (Tera Blast Poison)",
      type: ["psychic", "poison"],
      meta: [""],
    },
    {
      name: "Espeon (Tera Blast Ground)",
      type: ["psychic", "ground"],
      meta: [""],
    },
    {
      name: "Espeon (Tera Blast Flying)",
      type: ["psychic", "flying"],
      meta: [""],
    },
    {
      name: "Espeon (Tera Blast Bug)",
      type: ["psychic", "bug"],
      meta: [""],
    },
    {
      name: "Espeon (Tera Blast Rock)",
      type: ["psychic", "rock"],
      meta: [""],
    },
    {
      name: "Espeon (Tera Blast Ghost)",
      type: ["psychic", "ghost"],
      meta: [""],
    },
    {
      name: "Espeon (Tera Blast Dark)",
      type: ["psychic", "dark"],
      meta: [""],
    },
    {
      name: "Espeon (Tera Blast Dragon)",
      type: ["psychic", "dragon"],
      meta: [""],
    },
    {
      name: "Espeon (Tera Blast Steel)",
      type: ["psychic", "steel"],
      meta: [""],
    },
    {
      name: "Espeon (Tera Blast Fairy)",
      type: ["psychic", "fairy"],
      meta: [""],
    },
    {
      name: "Umbreon",
      type: ["dark", "ghost"],
      meta: [""],
    },
    {
      name: "Umbreon (Tera Blast Normal)",
      type: ["dark", "ghost", "normal"],
      meta: [""],
    },
    {
      name: "Umbreon (Tera Blast Fire)",
      type: ["dark", "ghost", "fire"],
      meta: [""],
    },
    {
      name: "Umbreon (Tera Blast Water)",
      type: ["dark", "ghost", "water"],
      meta: [""],
    },
    {
      name: "Umbreon (Tera Blast Grass)",
      type: ["dark", "ghost", "grass"],
      meta: [""],
    },
    {
      name: "Umbreon (Tera Blast Electric)",
      type: ["dark", "ghost", "electric"],
      meta: [""],
    },
    {
      name: "Umbreon (Tera Blast Ice)",
      type: ["dark", "ghost", "ice"],
      meta: [""],
    },
    {
      name: "Umbreon (Tera Blast Fighting)",
      type: ["dark", "ghost", "fighting"],
      meta: [""],
    },
    {
      name: "Umbreon (Tera Blast Poison)",
      type: ["dark", "ghost", "poison"],
      meta: [""],
    },
    {
      name: "Umbreon (Tera Blast Ground)",
      type: ["dark", "ghost", "ground"],
      meta: [""],
    },
    {
      name: "Umbreon (Tera Blast Flying)",
      type: ["dark", "ghost", "flying"],
      meta: [""],
    },
    {
      name: "Umbreon (Tera Blast Psychic)",
      type: ["dark", "ghost", "psychic"],
      meta: [""],
    },
    {
      name: "Umbreon (Tera Blast Bug)",
      type: ["dark", "ghost", "bug"],
      meta: [""],
    },
    {
      name: "Umbreon (Tera Blast Rock)",
      type: ["dark", "ghost", "rock"],
      meta: [""],
    },
    {
      name: "Umbreon (Tera Blast Dragon)",
      type: ["dark", "ghost", "dragon"],
      meta: [""],
    },
    {
      name: "Umbreon (Tera Blast Steel)",
      type: ["dark", "ghost", "steel"],
      meta: [""],
    },
    {
      name: "Umbreon (Tera Blast Fairy)",
      type: ["dark", "ghost", "fairy"],
      meta: [""],
    },
    {
      name: "Leafeon",
      type: ["grass", "fighting"],
      meta: [""],
    },
    {
      name: "Leafeon(Tera Blast Normal)",
      type: ["grass", "fighting", "normal"],
      meta: [""],
    },
    {
      name: "Leafeon(Tera Blast Fire)",
      type: ["grass", "fighting", "fire"],
      meta: [""],
    },
    {
      name: "Leafeon(Tera Blast Water)",
      type: ["grass", "fighting", "water"],
      meta: [""],
    },
    {
      name: "Leafeon(Tera Blast Electric)",
      type: ["grass", "fighting", "electric"],
      meta: [""],
    },
    {
      name: "Leafeon(Tera Blast Ice)",
      type: ["grass", "fighting", "ice"],
      meta: [""],
    },
    {
      name: "Leafeon(Tera Blast Poison)",
      type: ["grass", "fighting", "poison"],
      meta: [""],
    },
    {
      name: "Leafeon(Tera Blast Ground)",
      type: ["grass", "fighting", "ground"],
      meta: [""],
    },
    {
      name: "Leafeon(Tera Blast Flying)",
      type: ["grass", "fighting", "flying"],
      meta: [""],
    },
    {
      name: "Leafeon(Tera Blast Psychic)",
      type: ["grass", "fighting", "psychic"],
      meta: [""],
    },
    {
      name: "Leafeon(Tera Blast Bug)",
      type: ["grass", "fighting", "bug"],
      meta: [""],
    },
    {
      name: "Leafeon(Tera Blast Rock)",
      type: ["grass", "fighting", "rock"],
      meta: [""],
    },
    {
      name: "Leafeon(Tera Blast Ghost)",
      type: ["grass", "fighting", "ghost"],
      meta: [""],
    },
    {
      name: "Leafeon(Tera Blast Dark)",
      type: ["grass", "fighting", "dark"],
      meta: [""],
    },
    {
      name: "Leafeon(Tera Blast Dragon)",
      type: ["grass", "fighting", "dragon"],
      meta: [""],
    },
    {
      name: "Leafeon(Tera Blast Steel)",
      type: ["grass", "fighting", "steel"],
      meta: [""],
    },
    {
      name: "Leafeon(Tera Blast Fairy)",
      type: ["grass", "fighting", "fairy"],
      meta: [""],
    },
    {
      name: "Glaceon",
      type: ["ice", "ghost"],
      meta: [""],
    },
    {
      name: "Glaceon(Tera Blast Normal)",
      type: ["ice", "ghost", "normal"],
      meta: [""],
    },
    {
      name: "Glaceon(Tera Blast Fire)",
      type: ["ice", "ghost", "fire"],
      meta: [""],
    },
    {
      name: "Glaceon(Tera Blast Water)",
      type: ["ice", "ghost", "water"],
      meta: [""],
    },
    {
      name: "Glaceon(Tera Blast Grass)",
      type: ["ice", "ghost", "grass"],
      meta: [""],
    },
    {
      name: "Glaceon(Tera Blast Electric)",
      type: ["ice", "ghost", "electric"],
      meta: [""],
    },
    {
      name: "Glaceon(Tera Blast Fighting)",
      type: ["ice", "ghost", "fighting"],
      meta: [""],
    },
    {
      name: "Glaceon(Tera Blast Poison)",
      type: ["ice", "ghost", "poison"],
      meta: [""],
    },
    {
      name: "Glaceon(Tera Blast Ground)",
      type: ["ice", "ghost", "ground"],
      meta: [""],
    },
    {
      name: "Glaceon(Tera Blast Flying)",
      type: ["ice", "ghost", "flying"],
      meta: [""],
    },
    {
      name: "Glaceon(Tera Blast Psychic)",
      type: ["ice", "ghost", "psychic"],
      meta: [""],
    },
    {
      name: "Glaceon(Tera Blast Bug)",
      type: ["ice", "ghost", "bug"],
      meta: [""],
    },
    {
      name: "Glaceon(Tera Blast Rock)",
      type: ["ice", "ghost", "rock"],
      meta: [""],
    },
    {
      name: "Glaceon(Tera Blast Dark)",
      type: ["ice", "ghost", "dark"],
      meta: [""],
    },
    {
      name: "Glaceon(Tera Blast Dragon)",
      type: ["ice", "ghost", "dragon"],
      meta: [""],
    },
    {
      name: "Glaceon(Tera Blast Steel)",
      type: ["ice", "ghost", "steel"],
      meta: [""],
    },
    {
      name: "Glaceon(Tera Blast Fairy)",
      type: ["ice", "ghost", "fairy"],
      meta: [""],
    },
    {
      name: "Sylveon",
      type: ["fairy", "normal"],
      meta: [""],
    },
    {
      name: "Sylveon(Terra Blast Fire)",
      type: ["fairy", "normal", "fire"],
      meta: [""],
    },
    {
      name: "Sylveon(Terra Blast Water)",
      type: ["fairy", "normal", "water"],
      meta: [""],
    },
    {
      name: "Sylveon(Terra Blast Grass)",
      type: ["fairy", "normal", "grass"],
      meta: [""],
    },
    {
      name: "Sylveon(Terra Blast Electric)",
      type: ["fairy", "normal", "electric"],
      meta: [""],
    },
    {
      name: "Sylveon(Terra Blast Ice)",
      type: ["fairy", "normal", "ice"],
      meta: [""],
    },
    {
      name: "Sylveon(Terra Blast Fighting)",
      type: ["fairy", "normal", "fighting"],
      meta: [""],
    },
    {
      name: "Sylveon(Terra Blast Poison)",
      type: ["fairy", "normal", "poison"],
      meta: [""],
    },
    {
      name: "Sylveon(Terra Blast Ground)",
      type: ["fairy", "normal", "ground"],
      meta: [""],
    },
    {
      name: "Sylveon(Terra Blast Flying)",
      type: ["fairy", "normal", "flying"],
      meta: [""],
    },
    {
      name: "Sylveon(Terra Blast Psychic)",
      type: ["fairy", "normal", "psychic"],
      meta: [""],
    },
    {
      name: "Sylveon(Terra Blast Bug)",
      type: ["fairy", "normal", "bug"],
      meta: [""],
    },
    {
      name: "Sylveon(Terra Blast Rock)",
      type: ["fairy", "normal", "rock"],
      meta: [""],
    },
    {
      name: "Sylveon(Terra Blast Ghost)",
      type: ["fairy", "normal", "ghost"],
      meta: [""],
    },
    {
      name: "Sylveon(Terra Blast Dark)",
      type: ["fairy", "normal", "dark"],
      meta: [""],
    },
    {
      name: "Sylveon(Terra Blast Dragon)",
      type: ["fairy", "normal", "dragon"],
      meta: [""],
    },
    {
      name: "Sylveon(Terra Blast Steel)",
      type: ["fairy", "normal", "steel"],
      meta: [""],
    },

    {
      name: "Dragonite",
      type: ["dragon", "water", "normal"],
      meta: [""],
    },
    {
      name: "Slowking",
      type: ["psychic", "water", "fire"],
      meta: [""],
    },
    {
      name: "Scizor",
      type: ["bug", "fighting", "grass", "steel"],
      meta: [""],
    },
    {
      name: "Heracross",
      type: ["bug", "fighting", "normal"],
      meta: [""],
    },
    {
      name: "Blissey",
      type: ["normal", "fairy"],
      meta: [""],
    },
    {
      name: "Tyranitar",
      type: ["rock", "dark"],
      meta: [""],
    },
    {
      name: "Pelipper",
      type: ["flying", "water"],
      meta: [""],
    },
    {
      name: "Gardevoir",
      type: ["psychic", "fairy"],
      meta: [""],
    },
    {
      name: "Breloom",
      type: ["grass", "fighting", "flying"],
      meta: [""],
    },
    {
      name: "Torkoal",
      type: ["fire", "normal"],
      meta: [""],
    },
    {
      name: "Salamence",
      type: ["dragon", "flying", "fire"],
      meta: [""],
    },
    {
      name: "Salamence (Tera Blast Normal)",
      type: ["dragon", "flying", "fire", "normal"],
      meta: [""],
    },
    {
      name: "Salamence (Tera Blast Water)",
      type: ["dragon", "flying", "fire", "water"],
      meta: [""],
    },
    {
      name: "Salamence (Tera Blast Grass)",
      type: ["dragon", "flying", "fire", "grass"],
      meta: [""],
    },
    {
      name: "Salamence (Tera Blast Electric)",
      type: ["dragon", "flying", "fire", "electric"],
      meta: [""],
    },
    {
      name: "Salamence (Tera Blast Ice)",
      type: ["dragon", "flying", "fire", "ice"],
      meta: [""],
    },
    {
      name: "Salamence (Tera Blast Fighting)",
      type: ["dragon", "flying", "fire", "fighting"],
      meta: [""],
    },
    {
      name: "Salamence (Tera Blast Poison)",
      type: ["dragon", "flying", "fire", "poison"],
      meta: [""],
    },
    {
      name: "Salamence (Tera Blast Ground)",
      type: ["dragon", "flying", "fire", "ground"],
      meta: [""],
    },
    {
      name: "Salamence (Tera Blast Psychic)",
      type: ["dragon", "flying", "fire", "psychic"],
      meta: [""],
    },
    {
      name: "Salamence (Tera Blast Bug)",
      type: ["dragon", "flying", "fire", "bug"],
      meta: [""],
    },
    {
      name: "Salamence (Tera Blast Rock)",
      type: ["dragon", "flying", "fire", "rock"],
      meta: [""],
    },
    {
      name: "Salamence (Tera Blast Ghost)",
      type: ["dragon", "flying", "fire", "ghost"],
      meta: [""],
    },
    {
      name: "Salamence (Tera Blast Dark)",
      type: ["dragon", "flying", "fire", "dark"],
      meta: [""],
    },
    {
      name: "Salamence (Tera Blast Steel)",
      type: ["dragon", "flying", "fire", "steel"],
      meta: [""],
    },
    {
      name: "Salamence (Tera Blast Fairy)",
      type: ["dragon", "flying", "fire", "fairy"],
      meta: [""],
    },
    {
      name: "Staraptor",
      type: ["flying", "normal", "fighting"],
      meta: [""],
    },
    {
      name: "Garchomp",
      type: ["dragon", "ground", "rock", "fire"],
      meta: [""],
    },
    {
      name: "Hippowdon",
      type: ["rock", "ground", "ice"],
      meta: [""],
    },
    {
      name: "Magnezone",
      type: ["steel", "electric", "normal"],
      meta: [""],
    },
    {
      name: "Gallade",
      type: ["psychic", "fighting", "flying"],
      meta: [""],
    },
    {
      name: "Amoonguss",
      type: ["grass", "poison", "dark"],
      meta: [""],
    },
    {
      name: "Haxorus",
      type: ["dragon", "dark", "normal", "bug"],
      meta: [""],
    },
    {
      name: "Hydreigon",
      type: ["dark", "dragon"],
      meta: [""],
    },
    {
      name: "Volcarona",
      type: ["fire", "bug", "flying"],
      meta: [""],
    },
    {
      name: "Talonflame",
      type: ["fire", "flying"],
      meta: [""],
    },
    {
      name: "Talonflame (Tera Blast Normal)",
      type: ["fire", "flying", "normal"],
      meta: [""],
    },
    {
      name: "Talonflame (Tera Blast Water)",
      type: ["fire", "flying", "water"],
      meta: [""],
    },
    {
      name: "Talonflame (Tera Blast Grass)",
      type: ["fire", "flying", "grass"],
      meta: [""],
    },
    {
      name: "Talonflame (Tera Blast Electric)",
      type: ["fire", "flying", "electric"],
      meta: [""],
    },
    {
      name: "Talonflame (Tera Blast Ice)",
      type: ["fire", "flying", "ice"],
      meta: [""],
    },
    {
      name: "Talonflame (Tera Blast Fighting)",
      type: ["fire", "flying", "fighting"],
      meta: [""],
    },
    {
      name: "Talonflame (Tera Blast Poison)",
      type: ["fire", "flying", "poison"],
      meta: [""],
    },
    {
      name: "Talonflame (Tera Blast Ground)",
      type: ["fire", "flying", "ground"],
      meta: [""],
    },
    {
      name: "Talonflame (Tera Blast Psychic)",
      type: ["fire", "flying", "psychic"],
      meta: [""],
    },
    {
      name: "Talonflame (Tera Blast Bug)",
      type: ["fire", "flying", "bug"],
      meta: [""],
    },
    {
      name: "Talonflame (Tera Blast Rock)",
      type: ["fire", "flying", "rock"],
      meta: [""],
    },
    {
      name: "Talonflame (Tera Blast Ghost)",
      type: ["fire", "flying", "ghost"],
      meta: [""],
    },
    {
      name: "Talonflame (Tera Blast Dark)",
      type: ["fire", "flying", "dark"],
      meta: [""],
    },
    {
      name: "Talonflame (Tera Blast Dragon)",
      type: ["fire", "flying", "dragon"],
      meta: [""],
    },
    {
      name: "Talonflame (Tera Blast Steel)",
      type: ["fire", "flying", "steel"],
      meta: [""],
    },
    {
      name: "Talonflame (Tera Blast Fairy)",
      type: ["fire", "flying", "fairy"],
      meta: [""],
    },
    {
      name: "Dragalge",
      type: ["dragon", "water", "poison"],
      meta: [""],
    },
    {
      name: "Clawitzer",
      type: ["water", "fighting", "dragon"],
      meta: [""],
    },
    {
      name: "Goodra",
      type: ["water", "poison", "dragon", "grass"],
      meta: [""],
    },
    {
      name: "Avalugg",
      type: ["steel", "ice", "normal"],
      meta: [""],
    },
    {
      name: "Lycanroc",
      type: ["rock", "dark"],
      meta: [""],
    },
    {
      name: "Toxapex",
      type: ["water", "poison"],
      meta: [""],
    },
    {
      name: "Mimikyu",
      type: ["fairy", "ghost", "grass"],
      meta: [""],
    },
    {
      name: "Corviknight",
      type: ["flying", "steel", "fighting", "dark"],
      meta: [""],
    },
    {
      name: "Pincurchin",
      type: ["electric", "poison", "water"],
      meta: [""],
    },
    {
      name: "Frosmoth",
      type: ["ice", "bug", "flying"],
      meta: [""],
    },
    {
      name: "Dragapult",
      type: ["ghost", "dragon", "electric", "fire"],
      meta: [""],
    },
    {
      name: "Pawmot",
      type: ["electric", "fighting"],
      meta: [""],
    },
    {
      name: "moushold",
      type: ["fairy", "normal", "fighting"],
      meta: [""],
    },
    {
      name: "Dachsbun",
      type: ["fairy", "normal", "dark"],
      meta: [""],
    },
    {
      name: "Garganacl",
      type: ["rock", "fighting", "steel"],
      meta: [""],
    },
    {
      name: "Armarouge",
      type: ["ghost", "fire", "psychic"],
      meta: [""],
    },
    {
      name: "Ceruledge",
      type: ["ghost", "fire", "psychic"],
      meta: [""],
    },
    {
      name: "Kilowattrel",
      type: ["flying", "electric", "normal"],
      meta: [""],
    },
    {
      name: "Mabosstiff",
      type: ["dragon", "fighting", "dark", "normal"],
      meta: [""],
    },
    {
      name: "Grafaiai",
      type: ["poison", "normal", "dark"],
      meta: [""],
    },
    {
      name: "toadscruel",
      type: ["grass", "ground", "ghost"],
      meta: [""],
    },
    {
      name: "Klawf",
      type: ["rock", "bug", "dark"],
      meta: [""],
    },
    {
      name: "Tinkaton",
      type: ["fairy", "steel", "dark"],
      meta: [""],
    },
    {
      name: "Bombirdier",
      type: ["rock", "dark", "flying"],
      meta: [""],
    },

    {
      name: "Revavroom",
      type: ["poison", "fire", "steel"],
      meta: [""],
    },
    {
      name: "Cyclizar",
      type: ["normal", "dragon", "dark"],
      meta: [""],
    },
    {
      name: "Orthworm",
      type: ["ground", "steel", "rock"],
      meta: [""],
    },
    {
      name: "Glimmora",
      type: ["poison", "rock", "normal"],
      meta: [""],
    },
    {
      name: "Cetitan",
      type: ["ice", "ground", "normal"],
      meta: [""],
    },
    {
      name: "Dondozo",
      type: ["water", "dragon", "steel", "ghost"],
      meta: [""],
    },
    {
      name: "Annihilape",
      type: ["ghost", "fighting"],
      meta: [""],
    },
    {
      name: "Clodsire",
      type: ["ground", "poison", "bug"],
      meta: [""],
    },
    {
      name: "Farigiraf",
      type: ["psychic", "normal", "fighting"],
      meta: [""],
    },
    {
      name: "Kingambit",
      type: ["dark", "steel"],
      meta: [""],
    },
    {
      name: "Baxcalibur",
      type: ["ice", "dragon", "fighting"],
      meta: [""],
    },
  ],
};

let pokeArray = {
  pokemon: [
    {
      name: "MissingNo.",
      type: null,
      meta: [""],
    },
    {
      name: "Sprigatito",
      type: ["grass"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Floragato",
      type: ["grass"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Meowscarada",
      type: ["grass", "dark"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Fuecoco",
      type: ["fire"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Crocalor",
      type: ["fire"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Skeledirge",
      type: ["fire", "ghost"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Quaxly",
      type: ["water"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Quaxwell",
      type: ["water"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Quaquaval",
      type: ["water", "fighting"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Lechonk",
      type: ["normal"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Oinkologne",
      type: ["normal"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Tarountula",
      type: ["bug"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Spidops",
      type: ["bug"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Nymble",
      type: ["bug"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Lokix",
      type: ["bug", "dark"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Hoppip",
      type: ["grass", "flying"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Skiploom",
      type: ["grass", "flying"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Jumpluff",
      type: ["grass", "flying"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Fletchling",
      type: ["flying", "normal"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Fletchinder",
      type: ["flying", "fire"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Talonflame",
      type: ["flying", "fire"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Pawmi",
      type: ["electric"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Pawmo",
      type: ["electric", "fighting"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Pawmot",
      type: ["electric", "fighting"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Houndour",
      type: ["dark", "fire"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Houndoom",
      type: ["dark", "fire"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Yungoos",
      type: ["normal"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Gumshoos",
      type: ["normal"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Skwovet",
      type: ["normal"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Greedent",
      type: ["normal"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Sunkern",
      type: ["grass"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Sunflora",
      type: ["grass"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Kricketot",
      type: ["bug"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Kricketune",
      type: ["bug"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Scatterbug",
      type: ["bug"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Spewpa",
      type: ["bug"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Vivillon",
      type: ["bug", "flying"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Combee",
      type: ["flying", "bug"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Vespiquen",
      type: ["flying", "bug"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Rookidee",
      type: ["flying"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Corvisquire",
      type: ["flying"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Corviknight",
      type: ["flying", "steel"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Happiny",
      type: ["normal"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Chansey",
      type: ["normal"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Blissey",
      type: ["normal"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Azurill",
      type: ["normal", "fairy"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Marill",
      type: ["fairy", "water"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Azumarill",
      type: ["fairy", "water"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Surskit",
      type: ["bug", "water"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Masquerain",
      type: ["bug", "flying"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Buizel",
      type: ["water"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Floatzel",
      type: ["water"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Wooper",
      type: ["poison", "ground"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Clodsire",
      type: ["poison", "ground"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Psyduck",
      type: ["water"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Golduck",
      type: ["water"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Chewtle",
      type: ["water"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Drednaw",
      type: ["water", "ground"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Igglybuff",
      type: ["normal", "fairy"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Jigglypuff",
      type: ["normal", "fairy"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Wigglytuff",
      type: ["normal", "fairy"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Ralts",
      type: ["psychic", "fairy"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Kirlia",
      type: ["psychic", "fairy"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Gardevoir",
      type: ["psychic", "fairy"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Gallade",
      type: ["psychic", "fighting"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Drowzee",
      type: ["psychic"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Hypno",
      type: ["psychic"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Gastly",
      type: ["ghost", "poison"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Haunter",
      type: ["ghost", "poison"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Gengar",
      type: ["ghost", "poison"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Tandemaus",
      type: ["normal"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Maushold",
      type: ["normal"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Pichu",
      type: ["electric"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Pikachu",
      type: ["electric"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Raichu",
      type: ["electric"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Fidough",
      type: ["fairy"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Dachsbun",
      type: ["fairy"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Slakoth",
      type: ["normal"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Vigoroth",
      type: ["normal"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Slaking",
      type: ["normal"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Bounsweet",
      type: ["grass"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Steenee",
      type: ["grass"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Tsareena",
      type: ["grass"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Smoliv",
      type: ["grass", "normal"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Dolliv",
      type: ["grass", "normal"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Arboliva",
      type: ["grass", "normal"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Bonsly",
      type: ["rock"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Sudowoodo",
      type: ["rock"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Rockruff",
      type: ["rock"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Lycanroc",
      type: ["rock"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Rolycoly",
      type: ["rock"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Carkol",
      type: ["rock", "fire"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Coalossal",
      type: ["rock", "fire"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Shinx",
      type: ["electric"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Luxio",
      type: ["electric"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Luxray",
      type: ["electric"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Starly",
      type: ["normal", "flying"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Staravia",
      type: ["normal", "flying"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Staraptor",
      type: ["normal", "flying"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Oricorio(Fire)",
      type: ["flying", "fire"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Oricorio(Electric)",
      type: ["flying", "electric"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Oricorio(Psychic)",
      type: ["flying", "psychic"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Oricorio(Ghost)",
      type: ["flying", "ghost"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Mareep",
      type: ["electric"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Flaaffy",
      type: ["electric"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Ampharos",
      type: ["electric"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Petilil",
      type: ["grass"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Lilligant",
      type: ["grass"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Shroomish",
      type: ["grass"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Breloom",
      type: ["grass", "fighting"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Applin",
      type: ["grass", "dragon"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Flapple",
      type: ["grass", "dragon"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Appletun",
      type: ["grass", "dragon"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Spoink",
      type: ["psychic"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Grumpig",
      type: ["psychic"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Squawkabilly",
      type: ["normal", "flying"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Misdreavus",
      type: ["ghost"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Mismagius",
      type: ["ghost"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Makuhita",
      type: ["fighting"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Hariyama",
      type: ["fighting"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Crabrawler",
      type: ["fighting"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Crabominable",
      type: ["fighting", "ice"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Salandit",
      type: ["poison", "fire"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Salazzle",
      type: ["poison", "fire"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Phanpy",
      type: ["ground"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Donphan",
      type: ["ground"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Cufant",
      type: ["steel"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Copperajah",
      type: ["steel"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Gible",
      type: ["dragon", "ground"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Gabite",
      type: ["dragon", "ground"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Garchomp",
      type: ["dragon", "ground"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Nacli",
      type: ["rock"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Naclstack",
      type: ["rock"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Garganacl",
      type: ["rock"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Wingull",
      type: ["water", "flying"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Pelipper",
      type: ["water", "flying"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Magikarp",
      type: ["water"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Gyarados",
      type: ["water", "flying"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Arrokuda",
      type: ["water"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Barraskewda",
      type: ["water"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Basculin",
      type: ["water"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Gulpin",
      type: ["poison"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Swalot",
      type: ["poison"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Meowth",
      type: ["normal"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Persian",
      type: ["normal"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Drifloon",
      type: ["ghost", "flying"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Drifblim",
      type: ["ghost", "flying"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Flabébé",
      type: ["fairy"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Floette",
      type: ["fairy"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Florges",
      type: ["fairy"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Diglett",
      type: ["ground"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Dugtrio",
      type: ["ground"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Torkoal",
      type: ["fire"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Numel",
      type: ["fire", "ground"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Camerupt",
      type: ["fire", "ground"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Bronzor",
      type: ["steel", "psychic"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Bronzong",
      type: ["steel", "psychic"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Axew",
      type: ["dragon"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Fraxure",
      type: ["dragon"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Haxorus",
      type: ["dragon"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Mankey",
      type: ["fighting"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Primeape",
      type: ["fighting"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Annihilape",
      type: ["fighting", "ghost"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Meditite",
      type: ["fighting", "psychic"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Medicham",
      type: ["fighting", "psychic"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Riolu",
      type: ["fighting"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Lucario",
      type: ["fighting", "steel"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Charcadet",
      type: ["fire"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Armarouge",
      type: ["fire", "psychic"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Ceruledge",
      type: ["fire", "ghost"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Barboach",
      type: ["water", "ground"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Whiscash",
      type: ["water", "ground"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Tadbulb",
      type: ["electric"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Bellibolt",
      type: ["electric"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Goomy",
      type: ["dragon"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Sliggoo",
      type: ["dragon"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Goodra",
      type: ["dragon"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Croagunk",
      type: ["poison", "fight"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Toxicroak",
      type: ["poison", "fight"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Wattrel",
      type: ["electric", "flying"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Kilowattrel",
      type: ["electric", "flying"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Eevee",
      type: ["normal"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Vaporeon",
      type: ["water"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Jolteon",
      type: ["electric"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Flareon",
      type: ["fire"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Espeon",
      type: ["psychic"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Umbreon",
      type: ["dark"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Leafeon",
      type: ["grass"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Glaceon",
      type: ["ice"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Sylveon",
      type: ["fairy"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Dunsparce",
      type: ["normal"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Dudunsparce",
      type: ["normal"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Deerling",
      type: ["normal", "grass"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Sawsbuck",
      type: ["normal", "grass"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Girafarig",
      type: ["normal", "psychic"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Farigiraf",
      type: ["normal", "psychic"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Grimer",
      type: ["poison"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Muk",
      type: ["poison"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Maschiff",
      type: ["dark"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Mabosstiff",
      type: ["dark"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Toxel",
      type: ["electric", "poison"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Toxtricity",
      type: ["electric", "poison"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Dedenne",
      type: ["electric", "fairy"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Pachirisu",
      type: ["electric"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Shroodle",
      type: ["poison", "normal"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Grafaiai",
      type: ["poison", "normal"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Stantler",
      type: ["normal"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Foongus",
      type: ["grass", "poison"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Amoonguss",
      type: ["grass", "poison"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Voltorb",
      type: ["electric"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Electrode",
      type: ["electric"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Magnemite",
      type: ["electric", "steel"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Magneton",
      type: ["electric", "steel"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Magnezone",
      type: ["electric", "steel"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Ditto",
      type: ["normal"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Growlithe",
      type: ["fire"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Arcanine",
      type: ["fire"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Teddiursa",
      type: ["normal"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Ursaring",
      type: ["normal"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Zangoose",
      type: ["normal"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Seviper",
      type: ["poison"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Swablu",
      type: ["flying", "normal"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Altaria",
      type: ["flying", "dragon"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Skiddo",
      type: ["grass"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Gogoat",
      type: ["grass"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Tauros(Fighting)",
      type: ["fighting"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Tauros(Water)",
      type: ["fighting", "water"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Tauros(Fire)",
      type: ["fighting", "fire"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Litleo",
      type: ["fire", "normal"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Pyroar",
      type: ["fire", "normal"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Stunky",
      type: ["dark", "poison"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Skuntank",
      type: ["dark", "poison"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Zorua",
      type: ["dark"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Zoroark",
      type: ["dark"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Sneasel",
      type: ["dark", "ice"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Weavile",
      type: ["dark", "ice"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Murkrow",
      type: ["dark", "flying"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Honchkrow",
      type: ["dark", "flying"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Gothita",
      type: ["psychic"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Gothorita",
      type: ["psychic"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Gothitelle",
      type: ["psychic"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Sinistea",
      type: ["ghost"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Polteageist",
      type: ["ghost"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Mimikyu",
      type: ["ghost", "fairy"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Klefki",
      type: ["steel", "fairy"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Indeedee",
      type: ["psychic", "normal"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Bramblin",
      type: ["grass", "ghost"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Brambleghast",
      type: ["grass", "ghost"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Toedscool",
      type: ["grass", "ground"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Toedscruel",
      type: ["grass", "ground"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Tropius",
      type: ["grass", "flying"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Fomantis",
      type: ["grass"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Lurantis",
      type: ["grass"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Klawf",
      type: ["rock"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Capsakid",
      type: ["grass"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Scovillain",
      type: ["grass", "fire"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Cacnea",
      type: ["grass"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Cacturne",
      type: ["grass", "dark"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Rellor",
      type: ["bug"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Rabsca",
      type: ["bug", "psychic"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Venonat",
      type: ["bug", "psychic"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Venomoth",
      type: ["bug", "psychic"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Pineco",
      type: ["bug"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Forretress",
      type: ["bug", "steel"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Scyther",
      type: ["bug", "flying"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Scizor",
      type: ["bug", "steel"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Heracross",
      type: ["bug", "fighting"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Flittle",
      type: ["psychic"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Espathra",
      type: ["psychic"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Hippopotas",
      type: ["ground"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Hippowdon",
      type: ["ground"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Sandile",
      type: ["ground"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Krokorok",
      type: ["ground", "dark"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Krookodile",
      type: ["ground", "dark"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Silicobra",
      type: ["ground"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Sandaconda",
      type: ["ground"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Mudbray",
      type: ["ground"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Mudsdale",
      type: ["ground"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Larvesta",
      type: ["fire", "bug"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Volcarona",
      type: ["fire", "bug"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Bagon",
      type: ["dragon"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Shelgon",
      type: ["dragon"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Salamence",
      type: ["dragon", "flying"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Tinkatink",
      type: ["fairy", "steel"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Tinkatuff",
      type: ["fairy", "steel"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Tinkaton",
      type: ["fairy", "steel"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Hatenna",
      type: ["psychic"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Hattrem",
      type: ["psychic"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Hatterene",
      type: ["psychic", "fairy"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Impidimp",
      type: ["dark", "fairy"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Morgrem",
      type: ["dark", "fairy"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Grimmsnarl",
      type: ["dark", "fairy"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Wiglett",
      type: ["water"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Wugtrio",
      type: ["water"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Bombirdier",
      type: ["flying", "dark"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Finizen",
      type: ["water"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Palafin",
      type: ["water"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Varoom",
      type: ["steel", "poison"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Revavroom",
      type: ["steel", "poison"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Cyclizar",
      type: ["dragon", "normal"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Orthworm",
      type: ["steel"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Sableye",
      type: ["ghost", "dark"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Shuppet",
      type: ["ghost"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Banette",
      type: ["ghost"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Falinks",
      type: ["fighting"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Hawlucha",
      type: ["fighting", "flying"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Spiritomb",
      type: ["ghost", "dark"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Noibat",
      type: ["flying", "dragon"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Noivern",
      type: ["flying", "dragon"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Dreepy",
      type: ["dragon", "dark"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Drakloak",
      type: ["dragon", "dark"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Dragapult",
      type: ["dragon", "dark"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Glimmet",
      type: ["rock", "poison"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Glimmora",
      type: ["rock", "poison"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Rotom",
      type: [""],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Greavard",
      type: ["ghost"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Houndstone",
      type: ["ghost"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Oranguru",
      type: ["normal", "psychic"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Passimian",
      type: ["fighting"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Komala",
      type: ["normal"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Larvitar",
      type: ["rock", "ground"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Pupitar",
      type: ["rock", "ground"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Tyranitar",
      type: ["rock", "dark"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Stonjourner",
      type: ["rock"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Eiscue",
      type: ["ice"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Pincurchin",
      type: ["electric"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Sandygast",
      type: ["ghost", "ground"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Palossand",
      type: ["ghost", "ground"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Slowpoke",
      type: ["water", "psychic"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Slowbro",
      type: ["water", "psychic"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Slowking",
      type: ["water", "psychic"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Shellos",
      type: ["water"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Gastrodon",
      type: ["water", "ground"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Shellder",
      type: ["water"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Cloyster",
      type: ["water", "ice"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Qwilfish",
      type: ["water", "poison"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Luvdisc",
      type: ["water"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Finneon",
      type: ["water"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Lumineon",
      type: ["water"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Bruxish",
      type: ["water", "psychic"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Alomomola",
      type: ["water"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Skrelp",
      type: ["water", "poison"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Dragalge",
      type: ["water", "poison"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Clauncher",
      type: ["water"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Clawitzer",
      type: ["water"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Tynamo",
      type: ["electric"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Eelektrik",
      type: ["electric"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Eelektross",
      type: ["electric"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Mareanie",
      type: ["poison", "water"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Toxapex",
      type: ["poison", "water"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Flamigo",
      type: ["flying", "fighting"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Dratini",
      type: ["dragon"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Dragonair",
      type: ["dragon"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Dragonite",
      type: ["dragon", "flying"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Snom",
      type: ["ice", "bug"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Frosmoth",
      type: ["ice", "bug"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Snover",
      type: ["ice", "grass"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Abomasnow",
      type: ["ice", "grass"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Delibird",
      type: ["ice", "flying"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Cubchoo",
      type: ["ice"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Beartic",
      type: ["ice"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Snorunt",
      type: ["ice"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Glalie",
      type: ["ice"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Froslass",
      type: ["ice", "ghost"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Cryogonal",
      type: ["ice"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Cetoddle",
      type: ["ice"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Cetitan",
      type: ["ice"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Bergmite",
      type: ["ice"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Avalugg",
      type: ["ice"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Rufflet",
      type: ["normal", "flying"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Braviary",
      type: ["normal", "flying"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Pawniard",
      type: ["dark", "steel"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Bisharp",
      type: ["dark", "steel"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Kingambit",
      type: ["dark", "steel"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Deino",
      type: ["dark", "dragon"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Zweilous",
      type: ["dark", "dragon"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Hydreigon",
      type: ["dark", "dragon"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Veluza",
      type: ["water", "psychic"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Dondozo",
      type: ["water"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Tatsugiri",
      type: ["water", "dragon"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Great Tusk",
      type: ["ground", "fighting"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Scream Tail",
      type: ["fairy", "psychic"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Brute Bonnet",
      type: ["grass", "dark"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Flutter Mane",
      type: ["ghost", "fairy"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Slither Wing",
      type: ["bug", "fighting"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Sandy Shocks",
      type: ["electric", "ground"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Iron Treads",
      type: ["steel", "Ground"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Iron Bundle",
      type: ["ice", "water"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Iron Hands",
      type: ["fighting", "electric"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Iron Jugulis",
      type: ["dark", "flying"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Iron Moth",
      type: ["fire", "poison"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Iron Thorns",
      type: ["rock", "electric"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Frigibax",
      type: ["dragon", "ice"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Arctibax",
      type: ["dragon", "ice"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Baxcalibur",
      type: ["dragon", "ice"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Gimmighoul",
      type: ["ghost"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Gholdengo",
      type: ["ghost", "steel"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Wo-Chien",
      type: ["dark", "grass"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Chien-Pao",
      type: ["dark", "ice"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Ting-Lu",
      type: ["dark", "ground"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Chi-Yu",
      type: ["dark", "fire"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Roaring Moon",
      type: ["dragon", "dark"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Iron Valiant",
      type: ["fairy", "fighting"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Koraidon",
      type: ["dragon", "fighting"],
      meta: [""],
      imageData: "Not In Use",
    },
    {
      name: "Miraidon",
      type: ["dragon", "electric"],
      meta: [""],
      imageData: "Not In Use",
    },
  ],
};

typeArray = [
  "normal",
  "fire",
  "water",
  "grass",
  "electric",
  "ice",
  "fighting",
  "poison",
  "ground",
  "flying",
  "psychic",
  "bug",
  "rock",
  "ghost",
  "dark",
  "dragon",
  "steel",
  "fairy",
];


//"Type"Strong as attacker is Super effective aginst Array
normalStrong = [""];
fireStrong = ["grass", "ice", "bug", "steel"];
waterStrong = ["fire", "ground", "rock"];
grassStrong = ["water", "ground", "rock"];
electricStrong = ["water", "flying"];
iceStrong = ["grass", "ground", "flying", "dragon"];
fightingStrong = ["normal", "ice", "rock", "dark", "steel"];
poisonStrong = ["grass", "fairy"];
groundStrong = ["fire", "electric", "poison", "rock", "steel"];
flyingStrong = ["grass", "fighting", "bug"];
psychicStrong = ["fighting", "poison"];
bugStrong = ["grass", "psychic", "dark"];
rockStrong = ["fire", "ice", "flying", "bug"];
ghostStrong = ["psychic", "ghost"];
darkStrong = ["psychic", "ghost"];
dragonStrong = ["dragon"];
steelStrong = ["ice","rock", "fairy"];
fairyStrong = ["fighting", "dark", "dragon"];

//"Type"Weak as attacker is Not Very Effictive aginst Array
normalWeak = ["rock", "steel"];
fireWeak = ["fire", "water", "rock", "dragon"];
waterWeak = ["water", "grass", "dragon"];
grassWeak = ["fire", "grass", "poison", "flying", "bug", "dragon", "steel"];
electricWeak = ["grass", "electric", "dragon"];
iceWeak = ["fire", "water", "ice", "steel"];
fightingWeak = ["poison", "flying", "psychic", "bug", "fairy"];
poisonWeak = ["poison", "ground", "rock", "ghost"];
groundWeak = ["grass", "bug"];
flyingWeak = ["electric", "rock", "steel"];
psychicWeak = ["psychic", "steel"];
bugWeak = ["fire", "fighting", "poison", "flying", "ghost", "steel", "fairy"];
rockWeak = ["fighting", "ground", "steel"];
ghostWeak = ["dark"];
dragonWeak = ["steel"];
darkWeak = ["fighting", "dragon", "fairy"];
steelWeak = ["fire", "water", "electric", "steel"];
fairyWeak = ["fire", "poison", "steel"];

//"Type"Immune as attacker does no damage to Array
normalImmune = ["ghost"];
fireImmune = [];
waterImmune = [];
grassImmune = [];
electricImmune = ["ground"];
iceImmune = [];
fightingImmune = ["ghost"];
poisonImmune = ["steel"];
groundImmune = ["flying"];
flyingImmune = [];
psychicImmune = ["dark"];
bugImmune = [];
rockImmune = [];
ghostImmune = ["normal"];
dragonImmune = ["fairy"];
darkImmune = [];
steelImmune = [];
fairyImmune = [];
